%%%NOTE: for help with latex symbols look here http://mirror.unl.edu/ctan/info/symbols/comprehensive/symbols-a4.pdf.
\documentclass[12pt]{article}
\usepackage{color}
\usepackage{cite}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
%\usepackage{pdflscape}        %single page landscape
                                %mode \begin{landscape} \end{landscape}
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{multicol} % \begin{multicols}{number of columns} \end{multicols}
% \usepackage{lineno} %add lines numbers 
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{Sweave}
\newcommand{\etal}{\textit{et al.}}
\usepackage{hyperref}  %\hyperref[label_name]{''link text''}
                       %\hyperlink{label}{anchor caption}
                       %\hypertarget{label}{link caption}
\linespread{1.5}

\title{Community Genetics Simulations}
\author{M.K. Lau}
%\date{}                                           % Activate to display a given date or no date

\begin{document}
\maketitle
%\linenumbers %%add line numbers

%\setcounter{tocdepth}{3}  %%activate to number sections
%\tableofcontents

%\thispagestyle{empty}
%\setcounter{page}{0}
%\setcounter{secnumdepth}{-1}  %activate to start numbering from one
%on the second page

\section{25 Feb 2014}

New analysis structure for manuscript:

\begin{enumerate}
\item Genotype effect on network structure
\item Genotype effect on co-occurrence patterns
\item Selection effect on network structure
\end{enumerate}

Modeling and simulation process
\begin{enumerate}
\item These are handled by mkComs.R
\item Generate communities with even species total abundances
\item Generate communities with asymptotic total abundances using gpm
  from even communities
\item Generate null communities for r00, r0, c1, r1 models
\item Get network and co-occurrence statistics:
  \begin{enumerate}
  \item Get nestedness 
  \item Get modularity
  \item Get co-occurrence ses
  \end{enumerate}
\item Conduct selection:
  \begin{enumerate}
  \item directional
  \item stabilizing
  \item disruptive
  \end{enumerate}
\end{enumerate}

\section{6 Feb 2014}

Transferred files from research folder. Three script files:

\begin{enumerate}
\item een.R = nestedness and co-occurrence patterns
\item een_sym.R and een_asym.R = coupled set of simulations examining
  species removal
\end{enumerate}

Outputs are sent to results and data contains files for coupled
simulations. 

%\subsection{}

%% %%Figure construction
%% <<echo=false,results=hide,label=fig1,include=false>>=
%% @ 


%% %%Figure plotting
%% \begin{figure} 
%% \begin{center} 
%% <<label=fig1,fig=TRUE,echo=false>>=
%% <<fig1>> 
%% @ 
%% \end{center} 
%% \caption{}
%% \label{fig:one}
%% \end{figure}


%% %%Activate for bibtex vibliography
%% \cite{goossens93}
%% \bibliographystyle{plain}
%% \bibliography{/Users/Aeolus/Documents/bibtex/biblib}


\end{document}  


